// OpenVGAL Viewer Configuration
// Generated by OpenVGAL Generator
//
// Deployment path: '.' means relative to viewer.html — works in any subfolder.
// Examples:
//   Root:      https://example.com/          -> keep '.'
//   Subfolder: https://example.com/gallery/  -> keep '.'
//   Custom:    set to '/my/path' if assets are served from a different location
var openvgal_location = '.';

var glb_location = openvgal_location + '/templates/';
var config_file_name = openvgal_location + '/building_v2.json';
var materials_folder = openvgal_location + '/materials';
var hallspics_prefix = openvgal_location + '';
window.resolveImageUrl = function(path) { return hallspics_prefix + path; };

// Program constants
var regul_exp_door = /^d_/;
var regul_exp_tail = /_[0-9]*$/;
var regul_exp_artworks = /_\d{1,3}$/;
var frame_material = "BJS_white";
